name: Build and Push to Client Repo

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Project
        env:
          VITE_BASE_PATH: /soft/
        run: npm run build

      - name: Push Build to Client Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.CLIENT_GITHUB_TOKEN }}
          external_repository: rmautomob/soft
          publish_branch: main
          publish_dir: ./dist
          force_orphan: true
